name: ci

on:
  push:

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      -
        name: Set up Docker
        uses: docker/setup-docker-action@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitLab Container Registry
        run: echo "${{ secrets.GITLAB_REGISTRY_PASSWORD }}" | docker login registry.gitlab.com -u "${{ secrets.GITLAB_REGISTRY_USERNAME }}" --password-stdin
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gitlab.com/t2p2/registry/udemy:latest
